jobs:
  include:

    - stage: Unit Testing
      language: dart
      dist: xenial
      addons:
        apt:
          packages:
            - lib32stdc++6
      install:
        - git clone https://github.com/flutter/flutter.git -b stable
        - ./flutter/bin/flutter doctor
      script:
        - ./flutter/bin/flutter test --coverage
      after_success:
        - bash <(curl -s https://codecov.io/bash)
      cache:
        directories:
          - $HOME/.pub-cache

    - stage: Integration Testing
      os: osx
      osx_image: xcode11.7
      env: running driver on simulator
      # Run integration tests on ios
      before_install:
        - open /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app
        - brew update
        - brew install libimobiledevice
        - brew install ideviceinstaller
        - brew install ios-deploy
        - brew install cocoapods || echo 'ignore exit(1)'
        - brew link --overwrite cocoapods
        - git clone https://github.com/flutter/flutter.git -b beta
        - export PATH="$PATH":"$HOME/.pub-cache/bin"
        - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
        - flutter precache
        - flutter doctor -v
        - flutter devices
      script: travis_retry flutter driver test_driver/main.dart --flavor integration